type Query {
    users(
        pagination: Pagination
        search: String
    ): [User]!
}

type User {
    user_id: String
    username: String
    contact: String
}

type Mutation {
    addUser(
        username: String! contact: String!
    ): MutationResponse!
}
